baseurl = "/"
title = "MitchThinks"

theme = "hugo-coder"

languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

# disqusShortname = "yourdiscussshortname"

math = true

[params]
    author = "Mitchel Fruin"
    description = "Mitchel Fruin's personal website"
    keywords = "blog,data science,personal"
    info = "Junior Data Scientist"
    avatarurl = "images/Mitch_Headshot_Colour.jpg"
    footercontent = "A man must have (a) code."

    dateformat = "Jan 2, 2006"

    hideCredits = false
    hideCopyright = false

    # Git Commit in Footer, uncomment the line below to enable it.
    commit = "https://github.com/luizdepra/hugo-coder/tree/"

    rtl = false

    # Use inverted colors
    inverted = false

    # Series see also post count
    maxSeeAlsoItems = 5
    
    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    [[params.social]]
        name = "Github"
        icon = "fab fa-github"
        weight = 1
        url = "https://github.com/mitchelfruin"
    [[params.social]]
        name = "LinkedIn"
        icon = "fab fa-linkedin"
        weight = 2
        url = "https://www.linkedin.com/in/mitchelfruin/"
    [[params.social]]
        name = "Kaggle"
        icon = "fab fa-kaggle"
        weight = 3
        url = "https://www.kaggle.com/mitchelfruin"
    [[params.social]]
        name = "DataCamp"
        icon = "fas fa-database"
        weight = 4
        url = "https://www.datacamp.com/profile/mitchelfruin"

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[[menu.main]]
    name = "Posts"
    weight = 1
    url = "posts/"
[[menu.main]]
    name = "About"
    weight = 2
    url = "about/"
        